name: aws-cdk-2.178.2
channels:
  - conda-forge
dependencies:
  - python=3.13
  - nodejs<=20.0.0
  - pip
  - pipenv
  - pip:
    - aws-cdk-lib==2.178.2
    - constructs>=10.0.0
    - boto3>=1.28.15
    - botocore>=1.31.15